services:
  chunk-manager-1:
    build: ./storage
    container_name: chunk-container-1
    ports:
      - "8081:5000"
      - "2201:22"
    volumes:
      - chunk_storage_1:/chunks

  chunk-manager-2:
    build: ./storage
    container_name: chunk-container-2
    ports:
      - "8082:5000"
      - "2202:22" 
    volumes:
      - chunk_storage_2:/chunks

  chunk-manager-3:
    build: ./storage
    container_name: chunk-container-3
    ports:
      - "8083:5000"
      - "2203:22"  
    volumes:
      - chunk_storage_3:/chunks

  mysql-db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["mysqld", "--bind-address=0.0.0.0"] 

volumes:
  chunk_storage_1:
  chunk_storage_2:
  chunk_storage_3:
  mysql_data:
