version: "3.8"

services:
  chunk-manager-1:
    build: ./storage
    container_name: chunk-container-1
    ports:
      - "8081:5000"
    volumes:
      - chunk_storage_1:/chunks

  chunk-manager-2:
    build: ./storage
    container_name: chunk-container-2
    ports:
      - "8082:5000"
    volumes:
      - chunk_storage_2:/chunks

  chunk-manager-3:
    build: ./storage
    container_name: chunk-container-3
    ports:
      - "8083:5000"
    volumes:
      - chunk_storage_3:/chunks

volumes:
  chunk_storage_1:
  chunk_storage_2:
  chunk_storage_3:
